name: Allowance Extension Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: lnbits
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        # Install LNBits and dependencies
        git clone https://github.com/lnbits/lnbits.git
        cd lnbits
        poetry install
        cd ..
        
    - name: Install Playwright
      run: |
        npm init -y
        npm install playwright
        npx playwright install chromium
        
    - name: Setup LNBits environment
      run: |
        cd lnbits
        cp .env.example .env
        # Configure for testing
        echo "LNBITS_BACKEND_WALLET_CLASS=VoidWallet" >> .env
        echo "LNBITS_DATABASE_URL=postgres://postgres:postgres@localhost:5432/lnbits" >> .env
        echo "LNBITS_EXTENSIONS_DEFAULT_INSTALL=allowance" >> .env
        
    - name: Copy allowance extension
      run: |
        cp -r . lnbits/lnbits/extensions/allowance/
        
    - name: Start LNBits
      run: |
        cd lnbits
        poetry run python -m lnbits &
        echo $! > lnbits.pid
        # Wait for LNBits to start
        sleep 30
        curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost:5000/
        
    - name: Run admin account creation test
      run: |
        cd tests
        node create-admin-account.js
        
    - name: Enable allowance extension
      run: |
        cd tests
        node enable-allowance.js
        
    - name: Run allowance creation tests
      run: |
        cd tests
        # Test different frequencies
        node create-allowance.js "Test Daily" 50 daily
        node create-allowance.js "Test Weekly" 100 weekly
        node create-allowance.js "Test Monthly" 200 monthly
        node create-allowance.js "Test Hourly" 25 hourly
        node create-allowance.js "Test Minutely" 10 minutely
        
    - name: Run allowance edit tests
      run: |
        cd tests
        node edit-allowance.js "Test Daily" "Updated Daily" 75 weekly
        
    - name: Run allowance delete tests
      run: |
        cd tests
        node delete-allowance.js "Updated Daily"
        
    - name: Run minutely payments test (short version)
      run: |
        cd tests
        # Run for 2 minutes instead of 5 for CI
        timeout 150 node test-minutely-payments.js || true
        
    - name: Clear all allowances
      run: |
        cd tests
        node clear-all-allowances.js
        
    - name: Upload test screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-screenshots
        path: tests/test-results/
        
    - name: Stop LNBits
      if: always()
      run: |
        cd lnbits
        if [ -f lnbits.pid ]; then
          kill $(cat lnbits.pid) || true
        fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy
        
    - name: Run Black formatter check
      run: black --check .
      
    - name: Run Flake8 linter
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
    - name: Run MyPy type checker
      run: mypy . --ignore-missing-imports